[package]
name = "web"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "drydrop-web"
path = "src/main.rs"

[dependencies]
drydrop = { path = "../../crates/drydrop", features = ["web"] }

dioxus = { workspace = true, features = ["web"] }
dioxus-components = { path = "../../crates/dioxus-components" }
