[package]
name = "web"
version = "0.1.0"
edition = "2024"

[features]
default = ["web"]
web = ["dioxus/web", "drydrop/web"]

[dependencies]
drydrop = { path = "../../crates/drydrop", default-features = false }

dioxus = { workspace = true }
dioxus-components = { path = "../../crates/dioxus-components" }
