[workspace]
resolver = "3"
members = [
    "crates/*",
    "apps/*"
]

[workspace.dependencies]
# Server
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["cookie"] }

# Desktop + Mobile + Web
dioxus = { version = "0.7.10", features = ["fullstack", "router"] }
icons = { version = "0.18.3", features = ["dioxus"] }

# TUI
ratatui = { version = "0.30.2", features = ["all-widgets", "serde"] }
crossterm = { version = "0.29.0" }

# CLI
usage = { version = "6.8.0", package = "usage-rs" }

# Async trait
async-trait = { version = "0.1.92" }
# Config
dotenvy = { version = "0.15.7" }
config = { version = "0.15.25" }
# Serialize / Deserialize
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
# Uuid
uuid = { version = "1.26.0", features = ["serde", "v7", "js"] }
# Time
jiff = { version = "0.2.37", features = ["serde"] }
time = { version = "0.3.55" }
# Password hashing
argon2 = { version = "0.6.0" }
# JWT
jsonwebtoken = { version = "11.1.0", features = ["rust_crypto"] }
# Middleware
tower-http = { version = "0.7.1", features = ["full"] }
tower = { version = "0.5.3", features = ["full"] }
# OpenAPI
utoipa = { version = "5.5.0", features = ["axum_extras", "chrono", "uuid", "debug"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }
# Log
tracing-subscriber = { version = "0.3.23", features = ["fmt", "json", "env-filter"] }
tracing-appender = { version = "0.2.5" }
tracing = { version = "0.1.44" }
# Mail
check-if-email-exists = { version = "0.11.7" }
resend-rs = { version = "0.32.0" }
# Error handling for lib
thiserror = { version = "2.0.20" }
# Error handling for app
snafu = { version = "0.9.2" }
# Async runtime
tokio = { version = "1.53.1", features = ["full"] }
# Local cache
moka = { version = "0.12.16" }
# Redis connector
redis = { version = "1.6.0" }
# SQL
toasty = { version = "0.10.0", features = ["postgresql", "jiff"] }
# Message Queue
rabbitmq-stream-client = { version = "0.11.0" }
