[tasks.dev-up]
run = [
  'rm -rf postgres',
  'rm -rf redis',
  'rm -rf rabbitmq',
  'docker compose --env-file ../../config/.env.dev up -d',
]

[tasks.dev-down]
run = 'docker compose --env-file ../../config/.env.dev down'
