[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "drydrop-desktop"
path = "src/main.rs"

[dependencies]
drydrop = { path = "../../crates/drydrop", features = ["desktop"] }

dioxus = { workspace = true, features = ["desktop"] }
dioxus-components = { path = "../../crates/dioxus-components" }
