[tasks.macos-dev]
run = 'RUST_ENV=dev dx serve --macos'

[tasks.windows-dev]
run = 'RUST_ENV=dev dx serve --windows'

[tasks.macos-build]
run = 'dx bundle --macos --package-types "macos" --package-types "dmg"'

[tasks.windows-build]
run = 'dx bundle --desktop --package-types "nsis" --package-types "msi"'
